# Site settings
title: SSH implementation comparison
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A technical comparison of various SSH implementations (clients, servers and
  libraries), in terms of support SSH crypto protocols.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

exclude: [ssh-detect.py]

collections:
  impls:
    output: true

defaults:
  - scope:
      path: ""
      type: impls
    values:
      layout: impl
